name: Ticket Check

on:
  schedule:
    # Early morning check (7:00 AM CEST)
    - cron: '0 5 * * *'
    # Late morning check (10:00 AM CEST)
    - cron: '0 8 * * *'
    # After lunch check (1:00 PM CEST)
    - cron: '0 11 * * *'
    # Mid afternoon check (4:00 PM CEST)
    - cron: '0 14 * * *'
    # Evening check (7:00 PM CEST)
    - cron: '0 17 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  check-tickets:
    runs-on: ubuntu-latest

    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
      NODE_ENV: production
      XVFB_WHD: '1920x1080x24'
      DISPLAY: ':99.0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            chromium-browser \
            xvfb \
            libgbm-dev \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdrm2 \
            libxkbcommon0 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libgbm1 \
            libpango-1.0-0 \
            libcairo2 \
            libasound2

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
        run: |
          cat > .env << EOL
          EMAIL_USER=${EMAIL_USER}
          EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
          RECIPIENT_EMAILS=${RECIPIENT_EMAILS}
          SMTP_HOST=smtp.gmail.com
          SMTP_PORT=465
          EOL

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3

      - name: Run ticket checker
        run: |
          node src/github-action-runner.js 2>&1 | tee ticket_checker.log
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'

      - name: Stop Xvfb
        if: always()
        run: |
          pkill Xvfb || true

      - name: Upload error logs and screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs-${{ github.run_id }}
          path: |
            src/*.png
            *.log
            src/scraper_state.json
          retention-days: 7

      - name: Report status
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ Ticket check completed successfully at $(date)"
            echo "Events processed successfully. Check email for notifications."
          else
            echo "❌ Ticket check failed at $(date)"
            echo "Check the error logs for more details."
          fi
