name: Daily Ticket Check

on:
  schedule:
    - cron: '0 9 * * *' # 9:00 AM CEST (7:00 AM UTC)
  workflow_dispatch: # Allows manual execution of the workflow

jobs:
  check-tickets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci
          npm list

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          chromium-browser --version
          which chromium-browser

      - name: Create and verify .env file
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
        run: |
          echo "EMAIL_USER=${EMAIL_USER}" > src/.env
          echo "EMAIL_PASS=${EMAIL_PASS}" >> src/.env
          echo "RECIPIENT_EMAILS=${RECIPIENT_EMAILS}" >> src/.env

      - name: Run ticket checker
        run: |
          echo "Starting ticket checker..."
          node src/github-action-runner.js
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
          NODE_ENV: development
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-and-screenshots
          path: |
            src/*.png
            src/*.log
            src/.env
          if-no-files-found: warn
